[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "golden-retriever"
version = "0.0.0"
description = "A Python package."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [{ name = "Julia Haag" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[project.urls]
Repository = "https://github.com/tschuelia/golden-retriever"

[tool.hatch.build.targets.wheel]
packages = ["golden_retriever"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["golden_retriever"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "W"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
